### ISSUE TITLE
YAML pipeline definition

### ISSUE THREAD

**Issue by mfornasa** [ashwanthkumar/gocd-build-github-pull-requests#117]
I wonder if it's possible to trigger this in a pipeline defined in a YAML file.

**Comment by eddyseager** [comment]
It is using the pluggable scm e.g.

materials:
      myPluggableGit:
        # https://eu-gerrit-1.euhpc.arm.com/octopus/gocd-yaml/qe
        scm: 12345

**Comment by esselius** [comment]
Indeed this works

**Comment by mirogta** [comment]
```
# test.gocd.pipeline
...
    materials:
      test-git-pr:
        plugin_configuration:
          id: github.pr
          version: 1
        options:
          url: git@github.com:user/repository
…
```
