### ISSUE TITLE
Bitbucker PR will not trigger pipeline

### ISSUE THREAD

**Issue by patrijua** [ashwanthkumar/gocd-build-github-pull-requests#139]
Hi! I would need some help on how to use Stash Pull Requests Builder (https://github.com/ashwanthkumar/gocd-build-github-pull-requests) when pipelines are defined in yaml. Currently, I have a pipeline defined:
```
pipelines:
  bitbuketti: # name of pipeline
    group: Bitbucket
    materials:
      myPluggableGit: # name of material
        plugin_configuration:
          id: stash.pr
          version: 1.4.0-RC2
        options:
          url: https://[USERNAME]:[PASSWORD]@bitbucket.org/jpatrikainen/buketti.git
        destination: destinationDir
```
Pipeline was triggered when GoCD took this yml into use, it succesfully used material from master, but it will not trigger to any pull request I make in Bitbucket from some feature branches to master branch. Why it does not trigger? Should that "Default Branch" be defined in yml? If so, how?
