### ISSUE TITLE
Plugin doesn't work with yaml declared pipelines

### ISSUE THREAD

**Issue by insano10** [ashwanthkumar/gocd-build-github-pull-requests#90]
In GoCd 17.1:

When you declare a pipeline using the Github material in your repo using a yaml file, the poller doesn't trigger the pipeline. When you have the pipeline in the regular config.xml it works fine.

Could you hook into whatever mechanism the yaml plugin uses and trigger those pipelines too?

**Comment by ashwanthkumar** [comment]
Actually this plugin is an SCM material, it doesn't differentiate between running it from config.xml or yaml based trigger. As a matter of fact, we don't even know how the plugin is invoked. It's taken care internally by GoCD. 

Can you please share a sample yaml pipeline configuration that I can use for this purpose? I have never used YAML based configurations before.

**Comment by insano10** [comment]
Sure

```
# pipeline.gocd.yaml
pipelines:
  observation_deck_pr:
    group: pull_requests
    locking: on
    materials:
      observation_deck_pr_mat:
        git: git@github.com:insano10/observation-deck.git
        branch: master
        type: Github
        shallow_clone: true
    stages:
      - test:
          clean_workspace: true
          tasks:
            - exec:
                command: sbt
                arguments:
                  - clean
                  - compile
            - exec:
                command: sbt
                arguments:
                  - test
```

Let me know if you need any more info.

**Comment by marandalucas** [comment]
**Hi, I have the same problem. Plugin:**
https://github.com/tomzo/gocd-yaml-config-plugin

**You need configure your Config XML:**
  <config-repos>
    <config-repo plugin="yaml.config.plugin">
      <git url="git@github.com:DD/ci-gocd.git" />
    </config-repo>
  </config-repos> 

If you set the yaml of insane, you will see the next error "invalid or unknown materials "github""

**Comment by volodymyr-mykhailyk** [comment]
We solved this problem in following way. We define custom scm in cruise-config.xml:
```xml
    <scm id="my-project.pr" name="my-project.pr">
      <pluginConfiguration id="github.pr" version="1" />
      <configuration>
        <property>
          <key>url</key>
          <value>git@github.com:company/my-project.git</value>
        </property>
      </configuration>
    </scm>
```
After this we can use scm material in YAML configuration:
```
pipelines:
  my-project.pr:
    group: my-project
    materials:
      repo:
        scm: my-project.pr
        destination: repo
```
